on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
    - name: Versatile PyInstaller
      uses: sayyid5416/pyinstaller@v1.8.0
      with:
        python_ver: '3.13'
        spec: 'src/cleaner.spec'
        requirements: 'src/requirements.txt'
        upload_exe_with_name: 'PowerPoint Cleaner App.exe'
        options: --onefile, --name "PowerPoint Cleaner App", --windowed, 
    - name: Release
      uses: softprops/action-gh-release@v2
